# Generated by Django 5.2.12 on 2026-05-27 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_appointment_reminders", models.BooleanField(default=True)),
                ("email_appointment_status", models.BooleanField(default=True)),
                ("email_billing", models.BooleanField(default=True)),
                ("email_vaccination", models.BooleanField(default=True)),
                ("email_followup", models.BooleanField(default=True)),
                ("appointment_reminder_days", models.IntegerField(default=1)),
                ("vaccination_reminder_days", models.IntegerField(default=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
