# Generated by Django 5.2.12 on 2026-05-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petowner",
            name="address",
        ),
        migrations.AddField(
            model_name="petowner",
            name="address_line",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="petowner",
            name="barangay",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="petowner",
            name="city_municipality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="petowner",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
